### Get all games
GET http://localhost:3000/games

### Get all players
GET http://localhost:3000/players


### Create game
POST http://localhost:3000/games HTTP/1.1
Content-Type: application/json

{
    "title": "The Legend of Zelda: Breath of the Wild",
    "platform": "Nintendo Switch",
    "genre": "Action-Adventure",
    "developer": "Nintendo",
    "releaseYear": 2017,
    "rating": 5,
    "completed": true,
    "hoursPlayed": 120
}

### Create player
POST http://localhost:3000/players HTTP/1.1
Content-Type: application/json

{
    "username": "Spencer",
    "favoritePlatform": "PC",
    "favoriteGenre": "FPS",
    "gamesCompleted": 32
}


### Update game
PUT http://localhost:3000/games/6aae00874f8027fb9d8cf2a2 HTTP/1.1
Content-Type: application/json

{
    "title": "The Legend of Zelda: Breath of the Wild",
    "platform": "Nintendo Switch",
    "genre": "Action-Adventure",
    "developer": "Nintendo",
    "releaseYear": 2017,
    "rating": 5,
    "completed": true,
    "hoursPlayed": 126
}

### Update player
PUT http://localhost:3000/players/6aae00d74f8027fb9d8cf2a3 HTTP/1.1
Content-Type: application/json

{
    "username": "Spencer",
    "favoritePlatform": "PC",
    "favoriteGenre": "RPG",
    "gamesCompleted": 37
}

###DELETE game
DELETE http://localhost:3000/players/6aab3d459eb447328518f37d HTTP/1.1